[package]
name = "streamcompiler"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7.5"
pest_derive = "2.7.5"
inkwell = { version = "0.6.0", features = ["llvm18-1"] }
clap = { version = "4.5.41", features = ["derive"] }
